dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password:

rules:
  - !SHARDING
    tables:
      t_user:
        # Real data nodes
        actualDataNodes: ds_0.t_user${0..15}
        # Single table strategy
        tableStrategy:
          # Single table strategy
          standard:
            # Sharding column
            shardingColumn: username
            # Shard algorithm name
            shardingAlgorithmName: user_table_hash_mod
    shardingAlgorithms:
      user_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
props:
  sql-show: true